# -*- coding: utf-8 -*-
"""Assignment 2 Question 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TggBV7sDNodeiSWONt6NAgOIXmst5Xt
"""

li=[1,4,5,2,12]
li.remove(1)
print(li)
li.pop(2)
print(li)
li.remove(4)
print(li)
li.pop(1)
print(li)
li.remove(5)
print(li)

