# -*- coding: utf-8 -*-
"""Assignment 2 Question 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TggBV7sDNodeiSWONt6NAgOIXmst5Xt
"""

li=[1,2,4,12,5]
li.remove(1)
print(li)
li.remove(2)
print(li)
li.remove(4)
print(li)
li.remove(12)
print(li)
li.remove(5)
print(li)

